apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: finwise
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "finwise"
