import { Category, Transaction, AIRecommendation } from '../types';

export const mockCategories: Category[] = [
  // Income categories
  { id: '1', name: 'Зарплата', type: 'income', icon: '💼', color: '#10b981', isActive: true },
  { id: '2', name: 'Фриланс', type: 'income', icon: '💻', color: '#06b6d4', isActive: true },
  { id: '3', name: 'Инвестиции', type: 'income', icon: '📈', color: '#8b5cf6', isActive: true },
  
  // Expense categories
  { id: '4', name: 'Продукты', type: 'expense', icon: '🛒', color: '#f59e0b', isActive: true },
  { id: '5', name: 'Транспорт', type: 'expense', icon: '🚗', color: '#ef4444', isActive: true },
  { id: '6', name: 'Развлечения', type: 'expense', icon: '🎮', color: '#ec4899', isActive: true },
  { id: '7', name: 'Здоровье', type: 'expense', icon: '⚕️', color: '#14b8a6', isActive: true },
  { id: '8', name: 'Образование', type: 'expense', icon: '📚', color: '#3b82f6', isActive: true },
  { id: '9', name: 'ЖКХ', type: 'expense', icon: '🏠', color: '#6366f1', isActive: true },
  { id: '10', name: 'Одежда', type: 'expense', icon: '👕', color: '#a855f7', isActive: false },
];

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    amount: 85000,
    type: 'income',
    categoryId: '1',
    description: 'Зарплата за октябрь',
    date: new Date('2025-10-01'),
    userId: 'user1',
  },
  {
    id: '2',
    amount: 3500,
    type: 'expense',
    categoryId: '4',
    description: 'Продукты в супермаркете',
    date: new Date('2025-10-02'),
    userId: 'user1',
  },
  {
    id: '3',
    amount: 1200,
    type: 'expense',
    categoryId: '5',
    description: 'Метро и такси',
    date: new Date('2025-10-03'),
    userId: 'user1',
  },
  {
    id: '4',
    amount: 25000,
    type: 'income',
    categoryId: '2',
    description: 'Проект для клиента',
    date: new Date('2025-10-04'),
    userId: 'user1',
  },
  {
    id: '5',
    amount: 2800,
    type: 'expense',
    categoryId: '6',
    description: 'Кино и ресторан',
    date: new Date('2025-10-05'),
    userId: 'user1',
  },
  {
    id: '6',
    amount: 5500,
    type: 'expense',
    categoryId: '9',
    description: 'Коммунальные платежи',
    date: new Date('2025-10-06'),
    userId: 'user1',
  },
  {
    id: '7',
    amount: 4200,
    type: 'expense',
    categoryId: '4',
    description: 'Продукты на неделю',
    date: new Date('2025-10-07'),
    userId: 'user1',
  },
  {
    id: '8',
    amount: 1500,
    type: 'expense',
    categoryId: '7',
    description: 'Аптека',
    date: new Date('2025-10-08'),
    userId: 'user1',
  },
  {
    id: '9',
    amount: 8000,
    type: 'expense',
    categoryId: '8',
    description: 'Онлайн курс',
    date: new Date('2025-10-09'),
    userId: 'user1',
  },
  {
    id: '10',
    amount: 15000,
    type: 'income',
    categoryId: '3',
    description: 'Дивиденды',
    date: new Date('2025-10-10'),
    userId: 'user1',
  },
];

export const mockAIRecommendations: AIRecommendation[] = [
  {
    id: '1',
    title: 'Оптимизация расходов на продукты',
    description: 'За последний месяц траты на продукты выросли на 23%. Рекомендуем составить список покупок заранее и покупать по акциям.',
    category: 'saving',
    priority: 'high',
    potentialSavings: 2500,
  },
  {
    id: '2',
    title: 'Создайте накопительный фонд',
    description: 'У вас стабильный доход. Рекомендуем откладывать 15-20% от дохода в накопительный фонд для достижения финансовых целей.',
    category: 'saving',
    priority: 'high',
    potentialSavings: 17000,
  },
  {
    id: '3',
    title: 'Пересмотрите расходы на развлечения',
    description: 'Траты на развлечения составляют 8% от вашего бюджета. Можно сократить на 30% без потери качества жизни.',
    category: 'budget',
    priority: 'medium',
    potentialSavings: 1800,
  },
  {
    id: '4',
    title: 'Рассмотрите инвестиционные возможности',
    description: 'У вас есть свободные средства. Рассмотрите диверсификацию инвестиционного портфеля для увеличения пассивного дохода.',
    category: 'investment',
    priority: 'medium',
  },
];
